version: '3.9'
services: 
  docker:
    image: django-docker:0.01
    build: .
    command: >
          sh -c "python manage.py migrate &&
                python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"